# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*"


jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        set CGO_ENABLED=0
        set GOOS=windows& set GOARCH=amd64
        go build -o windows_build.exe -ldflags="-w -s"
        set GOOS=linux& set GOARCH=amd64
        go build -o linux_build -ldflags="-w -s"
        set GOOS=darwin& set GOARCH=arm64
        go build -o mac_build -ldflags="-w -s"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: hello-tags.exe
